DEEPSORT:
  REID_CKPT: "./deep_sort/deep_new/model_best_35classes.pth"
  MAX_DIST: 0.38
  MIN_CONFIDENCE: 0.30
  NMS_MAX_OVERLAP: 0.4
  MAX_IOU_DISTANCE: 0.0
  MAX_AGE: 700000
  N_INIT: 0
  NN_BUDGET: 1000
